# Ini adalah platform model pendanaan yang didukung

github: ['YinsXd']
community_bridge: AyiinMusicBot
custom: ['https://t.me/AyiinSupport', 'https://t.me/AyiinXdSupport']
github: ['Uputt-Userbot']
custom: ['https://t.me/uputtsupport', 'https://t.me/ohgitunih']
